### ISSUE TITLE
typescript error on create-post.ts

### ISSUE THREAD

**Issue by weisisheng** [conermurphy/cdk-tutorials#2]
New to typescript and ddb, when I try to build, I get the error on:

    key: { id: util.autoId() }, that " {id: string} " is not assignable to type {...} but clearly it is in schema.graphql, types/graphql.ts, and the mutations.ts file. And I performed the codegen step before. I tried to ts ignore the line, but still won't build. 

<>
export type CreatePostInput = {
  id?: string | null,
  title: string,
  description: string,
  author: string,
  publicationDate: string,
  pubStatus: PUBSTATUS,
  createdAt?: string | null,
};
</>

Appreciate any tips, help...

**Comment by weisisheng** [comment]
Bit of a blind truffle pig but believe one needs to add required to both IDs in type Post and CreatePostInput?

**Comment by conermurphy** [comment]
Hi @weisisheng,

Thanks for raising an issue on this. So, I also have the TS error with the `id` not included in the `CreatePostInput` type but this doesn't stop my CDK stack from building with `cdk synth` or deploying with `cdk deploy`. 

As you noted we can mark the `ID` as required in the `CreatePostInput` and `Post` to resolve the TS error but then this will cause requests that don't include `ID` in the body to return an error as the schema will be expecting an ID. So, if we did this it would make `util.autoId()` effectively pointless as it would never run.

In our schema file, we need to have `ID` as required on the `Post` type but `ID` NOT required on the `CreatePostInput` input type. This is because we want the `ID` on the input to be optional as users may want to provide it or they might want to allow the `util.autoId()` to automatically make an ID for them.

So, this leaves us with two options I believe.

1. As you noted we can perform a `// @ts-ignore` on the line to remove the TS error. _(Not ideal)_
2. Manually override the type we pass to `Context` to make the ID only required for that call which we can do with the below code.

```ts
import { put } from '@aws-appsync/utils/dynamodb';
import { Context, util } from '@aws-appsync/utils';
import { CreatePostInput, Post } from '../types/graphql';

interface UpdatePostInput extends Omit<CreatePostInput, 'id'> {
  id: string;
}

export function request(ctx: Context<{ input: UpdatePostInput }>) {
  return put({
    key: { id: util.autoId() },
    item: ctx.args.input,
  });
}

// ...response code
```

Ideally, we wouldn't need to do any of these and the types would just work but I believe the issue lies in the types being taken from the `Context` generic by the `put` function from `@aws-appsync/utils/dynamodb` as this expects the input to always have the `id` which isn't true as we might generate it in the request like we are. 

Let me know if this helps or if you have any other questions. 😄

**Comment by weisisheng** [comment]
Wow, thanks very much.  Tremendous insights.  i'll chew on this and do more study/hacking.  Thanks again.

**Comment by conermurphy** [comment]
No worries at all, happy to help 😄
